var blockShowNames = {
    "air": "空气",
    "stone": "石头",
    "granite": "花岗岩",
    "polished_granite": "磨制花岗岩",
    "diorite": "闪长岩",
    "polished_diorite": "磨制闪长岩",
    "andesite": "安山岩",
    "polished_andesite": "磨制安山岩",
    "grass": "草方块",
    "dirt": "泥土",
    "cobblestone": "原石",
    "oak_wood_planks": "橡木木板",
    "spruce_wood_planks": "云杉木板",
    "birch_wood_planks": "白桦木板",
    "jungle_wood_planks": "丛林木板",
    "acacia_wood_planks": "金合欢木板",
    "dark_oak_wood_planks": "深色橡木木板",
    "oak_sapling": "橡树树苗",
    "spruce_sapling": "云杉树苗",
    "birch_sapling": "白桦树苗",
    "jungle_sapling": "丛林树苗",
    "acacia_sapling": "金合欢树苗",
    "dark_oak_sapling": "深色橡树树苗",
    "bedrock": "基岩",
    "water": "水",
    "flowing_water": "流动的水",
    "lava": "熔岩",
    "flowing_lava": "流动的熔岩",
    "oak_log": "橡木",
    "spruce_log": "云杉木",
    "birch_log": "白桦木",
    "jungle_log": "丛林木",
    "oak_leaves": "橡树树叶",
    "spruce_leaves": "云杉树叶",
    "birch_leaves": "白桦树叶",
    "jungle_leaves": "丛林树叶",
    "glass": "玻璃",
    "acacia_leaves": "金合欢树叶",
    "dark_oak_leaves": "深色橡树树叶",
    "dandelion": "蒲公英",
    "poppy": "虞美人",
    "blue_orchid": "兰花",
    "allium": "绒球葱",
    "azure_bluet": "蓝花美耳草",
    "red_tulip": "红色郁金香",
    "orange_tulip": "橙色郁金香",
    "white_tulip": "白色郁金香",
    "pink_tulip": "粉红色郁金香",
    "oxeye_daisy": "滨菊",
    "crafting_table": "工作台",
    "cactus": "仙人掌",
    "glowstone": "萤石"
};

export {
    blockShowNames
};